FROM node:lts
#RUN apk add --no-cache python3 python3-dev
RUN set -ex && npm install -g node-sass@4.14  --unsafe-perm && npm install -g vue vue-cli vue-router create-react-app typescript gulp webpack
